# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12gGCyQTRjoMc_yUrOMY-wWolZVtwKYmg
"""

# libraries
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MultiLabelBinarizer
import pickle

df = pd.read_csv("BrewLogicMenu.csv")

# Split ingredients into binary flags
ingredients = df['Contains'].str.get_dummies(sep=';')
df = pd.concat([df, ingredients], axis=1)

# One-hot encode Flavor and Temperature
df = pd.get_dummies(df, columns=['Flavor', 'Temperature (usual)', 'Type'])

# Drop original Contains column
df = df.drop(columns=['Contains'])

df.head()

def recommend_drinks(preferences, df, top_n=5):
    # Define feature columns (exclude Product)
    feature_cols = [col for col in df.columns if col != 'Product']

    # Initialize query vector with zeros
    query = pd.DataFrame([[0]*len(feature_cols)], columns=feature_cols)

    # Fill query vector based on preferences
    for pref in preferences:
        for col in feature_cols:
            if pref.lower() in col.lower():
                query[col] = 1

    # Compute similarity (dot product)
    scores = (df[feature_cols].values @ query.values.T).ravel()

    # Rank products
    df['score'] = scores
    return df.sort_values('score', ascending=False).head(top_n)['Product']

recommend_drinks(["Chocolate", "Milk", "Hot"], df)